### PR TITLE
Refactor SourceBridge to PluginBridge and SourceEmbedded

### PR DESCRIPTION
**Pull request by werkshy**
We want to re-use the Source Bridge protocol for other iframe embedded purposes, notably embedded Connect applications inside customer applications. The plan is to:
a) Extract a general 'embedded' client that doesn't have anything plugin- specific.
b) Maintain a very similar API to the current SourceBridge as 'PluginBridge' , that uses the general embedded client.
c) Add a new 'Embedder' client for the parent applications.

This PR is (a) and (b).

Changes:
- Drop 'MessageType' string union since the generic client does not know about all of the different events applications might send (we will probably build that enum into the higher-level SDK that can embed e.g. a form iframe. We just use 'string' for message type fields at this level.
- Rename 'SourceBridge' to 'SourceEmbedded' and remove the plugin-specific API.
- Implement the old SourceBridge plugin API as PluginBridge.
- Move plugin-specific message interfaces to plugins/Messages.ts
- Rename existing tests to legacy_plugin
- Copy-paste plugin tests so that we are testing the new-style usage of PluginBridge as well as the backwards-compatible way.
- Update README
- Add CHANGELOG.md

### CODE REVIEW

**Comment by colinmorelli** [comment]
Keeping the authentication process in`SourceEmbedded` means that both plugins and embedded connect iframes need to have the same authentication structure, which isn't true today.

For example, the Carbon SDK refreshes tokens when the API indicates the current one is expired - it doesn't do so proactively. Similarly, it doesn't require the backend to return the expires_at alongside the JWT. We could get this information ourselves, by parsing the JWT, but that doesn't feel great for this.

I don't know if I have a suggestion yet, just voicing the feedback.

**Comment by werkshy** [comment]
> Keeping the authentication process in`SourceEmbedded` means that both plugins and embedded connect iframes need to have the same authentication structure, which isn't true today.
> 
> For example, the Carbon SDK refreshes tokens when the API indicates the current one is expired - it doesn't do so proactively. Similarly, it doesn't require the backend to return the expires_at alongside the JWT. We could get this information ourselves, by parsing the JWT, but that doesn't feel great for this.

Thanks for flagging that Carbon behavior, and I don't think the two token refresh mechanisms are compatible. If we wanted to keep the plugin auth system basically the same, we would do this:
1. Move 'Auth', the auth event, and `currentToken()` into the plugin-specific code (PluginBridge)
2. Our Connect apps would use a request/response token retrieval.
  i. Send an initial token in the handshake response (would be in the return value of `await BridgeGuest.init()`)
  ii. If Carbon-in-the-iframe detects the token has expired, it will ask the parent for a new token over Bridge as a request/response. The parent Carbon knows how to retrieve a new token already.

As an alternative, I think we could move plugins to request/response too, since `currentToken()` is already defined as async. The plugin can assume that the parent window always has a valid token (or else the parent window will have redirected to the login screen and unloaded the plugin). In this approach, retrieving a new token could be part of BridgeGuest, and we wouldn't need to include `expiresAt` in the auth response.

Because I am stacking PRs, I would probably choose to address this as a follow-on PR.

**Comment by colinmorelli** [comment]
Makes perfect sense to separate out that PR. The main difference I see with plugin auth is that those JWTs are intended to be consumed and used by customer-owned backend applications to verify the authenticity of the request. So we can't rely on our own API giving us back some indication that the token is invalid, causing a refresh. We'll still need to track some kind of expires_at field. But that might be worthwhile anyway.

Truthfully, I don't love the way Carbon handles auth right now. It works just fine, but I think we'd have a better experience if it more proactively refreshed tokens. After sleeping on it, I think I'd lean towards getting us closer to that direction rather than regressing the work you've done here to the current status quo.

**Review by zia-r — APPROVED** [review]

**Comment by werkshy** [comment]
Some aspects of this are changing in the next PR, but merging this now since it's approved for the v0.1 integration branch.

**Pull request merged**
